[package]
name = "api-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { version = "0.49.1", features = ["full"] }
reqwest = "0.12.20"
serde = "1.0.219"
serde_json = "1.0.140"
url = "2.5.4"
